### ISSUE TITLE
Bambu P1S recommended profile to use

### ISSUE THREAD

**Issue by chasebolt** [mjonuschat/OrcaSlicer-Profiles#1]
What profile would you recommend for printing voron parts on a bambu p1s?

**Comment by mjonuschat** [comment]
I have no experience with any Bambu printers, I would suggest printing some of the test parts from [here](https://github.com/VoronDesign/Voron-2/tree/Voron2.4/STLs/Test_Prints) with both profiles and comparing them, then picking the one with better results.
